### ISSUE TITLE
Course with bad number should be valid IFF exception is checked

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/tacos#55]
In case a course is new or hasn't been taught in years

**Comment by srkirkland** [comment]
Ex: ATM116

**Comment by jpknoll** [comment]
Would a warning be better?

Or is it always an exception if the calculation produces 0?

**Comment by srkirkland** [comment]
I think it's always an exception if the calc is 0.  Penny wants to be able to review why they are including a course we don't have with any calculated FTE.  Interesting question is what should we do if a course gets updated to be 0?  Don't have a good answer there, but something to think about

**Comment by jpknoll** [comment]
Eh, still probably not an exception. The production data has a few entries with calculated 0. I'm guessing the folks entering data are just adding all their courses without regard to the calculation. Were I them, I'd still want that course entered. If the updated course data resulted in a new TA, all the better for me, as I don't have to remember which course I'm not including because the calculation last year was zero.

I'm thinking the react-table with some filtering would make data entry easier.
